- hosts: 127.0.0.1
  connection: local
  become: yes
  vars_prompt:
    - name: zabbix_version
      prompt: "Which version would you like to install (5.0, 5.2)?"
      private: no
  tasks:
  - name: We need to define some facts :)
    set_fact:
      db_random_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digit,hexdigits')}}"
      zabbix_server_repo: "http://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_distribution.lower() }} {{ ansible_distribution_release }} main"
  - name: Install additional software
    apt:
      name: ca-certificates,nano,mc,vim,wget,curl,gnupg
      state: latest
  - name: Add gpg key
    apt_key:
      url: http://repo.zabbix.com/zabbix-official-repo.key
  - name: Add zabbix repository
    apt_repository:
      repo: "deb {{ zabbix_server_repo }}"
      state: present
  - name: Update cache
    apt:
      update_cache: yes
  - name: Install MariaDB, Zabbix and Zabbix frontend
    apt:
      name: mariadb-server,python3-pymysql,zabbix-agent,zabbix-frontend-php,zabbix-server-mysql,zabbix-apache-conf,zabbix-get
      state: present
  - name: Create database
    mysql_db:
        name: zabbix
        encoding: utf8
        collation: utf8_bin
        state: present
        login_user: root
        login_password: ''
        login_unix_socket: /var/run/mysqld/mysqld.sock
  - name: Create user and grant privileges
    mysql_user:
      name: zabbix
      password: "{{ db_random_password }}"
      priv: 'zabbix.*:ALL'
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock
  - name: Import zabbix database
    mysql_db:
      name: zabbix
      state: import
      target: /usr/share/doc/zabbix-server-mysql/create.sql.gz
      login_user: zabbix
      login_password: "{{ db_random_password }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
  - name: Set timezone in apache2 php.ini
    lineinfile: dest=/etc/php/7.3/apache2/php.ini
                regexp='date.timezone ='
                line='date.timezone = Europe/Bratislava'
  - name: Set DBPassword in zabbix_server.conf
    lineinfile: dest=/etc/zabbix/zabbix_server.conf
                regexp='DBPassword'
                line='DBPassword = {{ db_random_password }}'
  - name: Enable services in systemd
    systemd:
      name: "{{ item }}"
      enabled: yes
      masked: no
    with_items:
      - 'zabbix-agent'
      - 'zabbix-server'
  - name: Restart services
    systemd:
      name: "{{ item }}"
      state: restarted
    with_items:
      - 'zabbix-agent'
      - 'zabbix-server'
      - 'apache2'
  - template:
          src: zabbix.conf.php.conf
          dest: /etc/zabbix/web/zabbix.conf.php
          owner: www-data
          group: www-data
          mode: '0644'
  - name: Finish
    debug:
      msg:
        - "Your Zabbix Server installation is done, please go to: http://{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}/zabbix"
        - " - Username: Admin"
        - " - Password: zabbix"